# Generated by Django 4.2.6 on 2023-10-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_portfolioprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioprofile',
            name='dividends_target',
            field=models.FloatField(blank=True),
        ),
    ]
