# Generated by Django 4.2.6 on 2023-10-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_portfolioprofile_dividends_target'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioProfile',
        ),
    ]
