# Generated by Django 4.2.6 on 2023-11-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0006_alter_portfolioitems_sort_of_delete_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=10)),
                ('operation', models.CharField(choices=[('C', 'COMPRA'), ('V', 'VENDA'), ('A', 'SPLIT/AGRUP')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('sort_of', models.CharField(choices=[('AÇÕES', 'AÇÕES'), ('FIIS', 'FIIS'), ('SPLIT/AGRUP', 'SPLIT/AGRUP')], max_length=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
