# Generated by Django 4.2.6 on 2023-10-31 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=10)),
                ('operation', models.CharField(choices=[('C', 'COMPRA'), ('V', 'VENDA')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('type', models.CharField(choices=[('AÇÕES', 'AÇÕES'), ('FIIS', 'FIIS')], max_length=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('AÇÕES', 'AÇÕES'), ('FIIS', 'FIIS')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('average_price', models.FloatField()),
                ('portfolio_weight', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
