# Generated by Django 4.2.6 on 2023-10-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_type_portfolioitems_sort_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='dividends_target',
            field=models.FloatField(default=0.0),
        ),
    ]
