# Generated by Django 4.2.6 on 2023-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_dividends_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitems',
            name='sort_of',
            field=models.CharField(choices=[('AÇÕES', 'AÇÕES'), ('FIIS', 'FIIS'), ('Split/Agrup', 'Split/Agrup')], max_length=15),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='operation',
            field=models.CharField(choices=[('C', 'COMPRA'), ('V', 'VENDA'), ('A', 'Split/Agrup')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='sort_of',
            field=models.CharField(choices=[('AÇÕES', 'AÇÕES'), ('FIIS', 'FIIS'), ('Split/Agrup', 'Split/Agrup')], max_length=15),
        ),
    ]
