# Generated by Django 4.2.6 on 2023-11-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolioitems_sort_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitems',
            name='sort_of',
            field=models.CharField(choices=[('AÇÕES', 'AÇÕES'), ('FIIS', 'FIIS'), ('SPLIT/AGRUP', 'SPLIT/AGRUP')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
