# Generated by Django 4.2.6 on 2023-11-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfolioitems_sort_of_delete_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitems',
            name='average_price',
        ),
        migrations.RemoveField(
            model_name='portfolioitems',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='portfolioitems',
            name='sort_of',
        ),
    ]
