# Generated by Django 4.2.6 on 2023-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_portfolioitems_average_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitems',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
