# Generated by Django 4.2.6 on 2023-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolioitems_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitems',
            name='portfolio_weight',
            field=models.FloatField(default=50.0),
        ),
    ]
