# Generated by Django 4.2.6 on 2023-12-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_portfolioitems_portfolio_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitems',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
